### ISSUE TITLE
event-like algorithm chains

### ISSUE THREAD

**Issue by pjz** [gratipay/algorithm.py#8]
```
algorithm.on("key", algorithm_func) 
```
should add `algorithm_func` to a chain that gets executed after the `"key"` shows up in the state dict for the first time.

**Comment by whit537** [comment]
Can you subscribe to multiple keys?

**Comment by whit537** [comment]
Went round the horn on this on the [April 2015 Aspen call](https://www.youtube.com/watch?v=fgVeSOUO05Q), and decided not to go down this path because it's too complicated for the simplate case we were trying to support in https://github.com/gratipay/aspen-python/issues/424.
